DROP TABLE IF EXISTS "mark";
CREATE TABLE "mark" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "id_student" INTEGER, "id_subject" INTEGER, "mark" INTEGER);
INSERT INTO "mark" VALUES(1,1,1,4);
INSERT INTO "mark" VALUES(2,1,2,5);
DROP TABLE IF EXISTS "student";
CREATE TABLE "student" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" TEXT, "surname" TEXT, "middlename" TEXT);
INSERT INTO "student" VALUES(1,'Иван','Иванов','Иванович');
INSERT INTO "student" VALUES(2,'Пётр','Иванов','Иванович');
INSERT INTO "student" VALUES(3,'Пётр','Петров','Петрович');
INSERT INTO "student" VALUES(4,'Иван','Петров','Петрович');
INSERT INTO "student" VALUES(5,'Иван','Сидоров','Петрович');
INSERT INTO "student" VALUES(6,'Дмитрий','Медведев','Анатольевич');
INSERT INTO "student" VALUES(7,'Владимир','Путин','Владимирович');
DROP TABLE IF EXISTS "subject";
CREATE TABLE "subject" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "name" TEXT);
INSERT INTO "subject" VALUES(1,'ОБЖ');
INSERT INTO "subject" VALUES(2,'Математический Анализ');
INSERT INTO "subject" VALUES(3,'Химия');
INSERT INTO "subject" VALUES(4,'Физика');
