rename 01_template_min_max 31_template_min_max
rename 02_const
rename 02_operators
rename 02_template_duck_typing
rename 03_print_commas
rename 03_template_stack_queue
rename 04_template_int
rename 05_template_sum
06_template_sort
08_template_many_functions
09_vector
