#ifndef QTDLLEXAMPLE_GLOBAL_H
#define QTDLLEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTDLLEXAMPLE_LIBRARY)
#  define QTDLLEXAMPLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTDLLEXAMPLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTDLLEXAMPLE_GLOBAL_H
