DROP TABLE IF EXISTS "Mark";
CREATE TABLE "Mark" ("subject_id" INTEGER NOT NULL , "student_id" INTEGER NOT NULL , "id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "mark" INTEGER NOT NULL );
INSERT INTO "Mark" VALUES(1,2,1,2);
INSERT INTO "Mark" VALUES(1,2,2,2);
INSERT INTO "Mark" VALUES(1,1,3,1);
INSERT INTO "Mark" VALUES(1,1,4,1);
INSERT INTO "Mark" VALUES(1,2,5,2);
INSERT INTO "Mark" VALUES(5,4,6,4);
DROP TABLE IF EXISTS "Student";
CREATE TABLE "Student" ("likeSubject" NUMERIC,"id" INTEGER PRIMARY KEY ,"name" TEXT,"surname" TEXT,"phone" TEXT DEFAULT (null) ,"email" TEXT);
INSERT INTO "Student" VALUES(1,1,'Иван','Иванов',NULL,NULL);
INSERT INTO "Student" VALUES(4,2,'Пётр','Петров',NULL,NULL);
INSERT INTO "Student" VALUES(1,3,'Сидор','Сидоров',NULL,NULL);
INSERT INTO "Student" VALUES(1,4,'Иван','Петров',NULL,NULL);
INSERT INTO "Student" VALUES(NULL,5,'Маша','Петрова',NULL,NULL);
DROP TABLE IF EXISTS "Subject";
CREATE TABLE Subject (Количество_уроков NUMERIC, name TEXT, id INTEGER PRIMARY KEY);
INSERT INTO "Subject" VALUES(NULL,'История',1);
INSERT INTO "Subject" VALUES(2,'География',2);
INSERT INTO "Subject" VALUES(NULL,'Музыка',3);
INSERT INTO "Subject" VALUES(NULL,'Информатика',4);
INSERT INTO "Subject" VALUES(NULL,'Интересный предмет',5);
INSERT INTO "Subject" VALUES(NULL,'Труд',6);
DROP TABLE IF EXISTS "WithoutPK";
CREATE TABLE "WithoutPK" ("name" TEXT, "surname" TEXT);
INSERT INTO "WithoutPK" VALUES('12','1212');
INSERT INTO "WithoutPK" VALUES('12','1212');
